import numpy as np

# --- THAY ĐỔI BASE_DIR THÀNH ĐƯỜNG DẪN CỦA BẠN ---
BASE_DIR = "D:/baitapxaml/HK252/DATN/Main/shooting-scoring-system/cv" 

VIDEO_PATH = "D:/baitapxaml/HK252/DATN/DetectBullet/target5.mp4"
CV2_NUM_THREADS = 1
BACKEND_HTTP_URL = "http://localhost:8000"
BACKEND_WS_URL = "ws://localhost:8000/ws/shots"

PATH_IPSC_POLY = f"{BASE_DIR}/Scoring/IPSC/polygon.txt"
PATH_NGUOI_CONT = f"{BASE_DIR}/Scoring/Nguoi/Nguoi_contours.txt"

# Kích thước và Tọa độ
WIDTH, HEIGHT = 1240, 1754
SCALE_FACTOR = 2480 / WIDTH
MARGIN = 40
EXPECTED_RADIUS = 21.4  

dst_points = np.array([
    [MARGIN, MARGIN], 
    [WIDTH - MARGIN, MARGIN], 
    [WIDTH - MARGIN, HEIGHT - MARGIN], 
    [MARGIN, HEIGHT - MARGIN]
], dtype=np.float32)

# --- THÔNG SỐ TỐI ƯU MỚI ---
CIRCULARITY_THRESH = 0.5  # Chuẩn độ tròn mới (Bỏ qua overlap)
CONFIRM_FRAMES = 5         # Số frame liên tiếp để xác nhận đạn
STALE_FRAMES = 20          # Frame chờ trước khi xóa candidate
FORGET_FRAMES = 999999         # Frame chờ trước khi xóa confirmed
MATCH_DIST = 15            # Bán kính tìm kiếm ghép cặp (Hungarian)
CONFIRMED_SMOOTH_FRAMES = 3
BG_ALPHA = 0.05            # Tốc độ học nền mới (Rolling BG)

CONFIRMED_DUPLICATE_DIST = EXPECTED_RADIUS * 1
CONFIRMED_STRICT_DUPLICATE_DIST = EXPECTED_RADIUS * 0.85
SEQUENTIAL_DIFF_THRESH = 14
SEQUENTIAL_MIN_AREA = 120
SEQUENTIAL_DILATE_RADIUS = int(EXPECTED_RADIUS * 1.2)
NEW_EVIDENCE_DUPLICATE_MIN_AREA = 180


# --- HOUGH TUNING ---
HOUGH_DP = 1.0
HOUGH_MIN_DIST_FACTOR = 0.85
HOUGH_PARAM1 = 50
HOUGH_PARAM2 = 16
HOUGH_MIN_RADIUS_FACTOR = 0.6
HOUGH_MAX_RADIUS_FACTOR = 1.4


# --- RANSAC TUNING ---
RANSAC_MIN_CONTOUR_POINTS = 6
RANSAC_ITERATIONS = 120
RANSAC_HOUGH_REMOVE_THRESH = 5.0
RANSAC_INLIER_THRESH = 7
RANSAC_MIN_INLIERS = 6
RANSAC_MIN_AVAILABLE_POINTS = 6
NMS_MIN_DIST_FACTOR = 0.75

CIRCLE_CENTER_OUTSIDE_TOLERANCE_FACTOR = 0.45
CIRCLE_MIN_MASK_SUPPORT_RATIO = 0.18

ARUCO_DETECT_EVERY_N_FRAMES = 2
CONFIRMED_MASK_RADIUS_FACTOR = 1.0
